import { defineConfig } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
  plugins: [
    VitePWA({
      registerType: 'autoUpdate',
      injectRegister: 'script-defer',
      manifest: {
        name: 'Piano Keyboard',
        short_name: 'Piano',
        description: 'To play piano using CSS and JavaScript',
        theme_color: '#333333',
        background_color: '#333333',
        orientation: 'landscape',
        // Generated by `pnpm generate-pwa-assets`
        icons: [
          { src: 'images/pwa-64x64.png', sizes: '64x64', type: 'image/png' },
          { src: 'images/pwa-192x192.png', sizes: '192x192', type: 'image/png' },
          { src: 'images/pwa-512x512.png', sizes: '512x512', type: 'image/png' },
          { src: 'images/maskable-icon-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,ico,png,mp3}'],
        maximumFileSizeToCacheInBytes: 5 * 1024 * 1024,
      },
    }),
  ],
});
